import React from 'react';

interface SqlHelpProps {
  isOpen: boolean;
  onToggle: (isOpen: boolean) => void;
}

export const SqlHelp: React.FC<SqlHelpProps> = ({ isOpen, onToggle }) => {
  if (!isOpen) {
    return (
        <div className="mt-12 p-4 bg-gray-50 border border-gray-200 text-center rounded">
            <p className="text-xs text-gray-500 mb-2 font-sans">Need to update your database?</p>
            <button onClick={() => onToggle(true)} className="text-xs font-bold text-del-blue hover:underline uppercase tracking-wider">
                Show Database SQL Commands
            </button>
        </div>
    )
  }

  return (
    <div className="mt-8 p-6 bg-white border-2 border-del-blue font-sans shadow-lg">
      <div className="flex justify-between items-start mb-6">
        <div>
            <h3 className="font-bold text-lg text-black">Supabase Setup Guide</h3>
            <p className="text-sm text-gray-600">Copy the SQL blocks below into your Supabase SQL Editor.</p>
        </div>
        <button onClick={() => onToggle(false)} className="text-gray-400 hover:text-black text-xl">&times;</button>
      </div>

      <div className="space-y-8">
        <section className="bg-yellow-50 p-4 border border-yellow-200">
          <h4 className="font-bold text-xs uppercase text-black mb-2">Step 4: Add Notes Support (Latest)</h4>
          <p className="text-[11px] mb-2 text-gray-700">Run this to enable personal notes on bookmarks:</p>
          <div className="relative group">
            <pre className="bg-gray-900 text-gray-100 p-4 rounded text-[11px] font-mono overflow-x-auto whitespace-pre select-all">
{`alter table bookmarks add column notes text;`}
            </pre>
          </div>
        </section>

        <section className="bg-gray-50 p-4 border border-gray-200">
          <h4 className="font-bold text-xs uppercase text-black mb-2">Step 3: Add Folders Support</h4>
          <div className="relative group">
            <pre className="bg-gray-900 text-gray-100 p-4 rounded text-[11px] font-mono overflow-x-auto whitespace-pre select-all">
{`alter table bookmarks add column folders text[] default '{}';`}
            </pre>
          </div>
        </section>

        <section>
          <h4 className="font-bold text-xs uppercase text-del-blue mb-2">Step 1: Create Bookmarks Table (Initial Setup)</h4>
          <div className="relative group">
            <pre className="bg-gray-900 text-gray-100 p-4 rounded text-[11px] font-mono overflow-x-auto whitespace-pre select-all">
{`create table bookmarks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  url text not null,
  title text not null,
  description text,
  tags text[] default '{}',
  folders text[] default '{}',
  to_read boolean default false,
  user_id uuid references auth.users not null default auth.uid()
);

alter table bookmarks enable row level security;

create policy "Users can only see their own bookmarks" on bookmarks for select using (auth.uid() = user_id);
create policy "Users can insert their own bookmarks" on bookmarks for insert with check (auth.uid() = user_id);
create policy "Users can update their own bookmarks" on bookmarks for update using (auth.uid() = user_id);
create policy "Users can delete their own bookmarks" on bookmarks for delete using (auth.uid() = user_id);`}
            </pre>
            <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                <span className="bg-white/10 text-[10px] px-2 py-1 rounded">Click to select all</span>
            </div>
          </div>
        </section>

        <section>
          <h4 className="font-bold text-xs uppercase text-del-blue mb-2">Step 2: Setup Avatar Storage</h4>
          <div className="relative group">
            <pre className="bg-gray-900 text-gray-100 p-4 rounded text-[11px] font-mono overflow-x-auto whitespace-pre select-all">
{`insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true);

create policy "Avatar images are publicly accessible" on storage.objects for select using ( bucket_id = 'avatars' );
create policy "Anyone can upload an avatar" on storage.objects for insert with check ( bucket_id = 'avatars' AND auth.role() = 'authenticated' );`}
            </pre>
          </div>
        </section>
      </div>
      
      <button onClick={() => onToggle(false)} className="mt-6 w-full py-2 bg-gray-100 hover:bg-gray-200 text-xs font-bold uppercase tracking-widest transition-colors">
          Close Guide
      </button>
    </div>
  );
};